# Generated by Django 2.1.2 on 2018-10-03 00:00

import dj_bitfields.bitstringfield
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('schedule', dj_bitfields.bitstringfield.BitStringField(default=None, max_length=8)),
            ],
        ),
    ]
